version: '3.7'
services:
  db:
    image: postgres:11
    ports:
      - '5432:5432'
    volumes:
       - ./postgresql/data:/var/lib/postgresql/data
    environment:
       POSTGRES_PASSWORD: "admin"
       POSTGRES_USER: "admin"
       POSTGRES_DB: "lottodo"
    restart: always